In [24]:
import torch
import torchvision
import numpy as np

In [2]:
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [4]:
x = torch.Tensor(5, 3)
print(x)

tensor([[-2.3829e-10,  9.8792e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [9]:
x = torch.rand(5, 3)
print(x)
print(x.size()[1])

tensor([[0.2305, 0.7139, 0.0871],
        [0.7559, 0.9948, 0.3184],
        [0.1984, 0.6336, 0.7267],
        [0.6210, 0.3999, 0.4735],
        [0.8516, 0.1729, 0.2331]])
3


In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.3289, 1.3641, 0.7257],
        [1.7130, 1.0656, 0.6474],
        [0.6503, 1.2145, 1.4731],
        [1.6164, 0.8102, 0.7954],
        [1.6623, 1.0925, 0.8558]])


In [13]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)
print(result[:, 1])

tensor([[0.3289, 1.3641, 0.7257],
        [1.7130, 1.0656, 0.6474],
        [0.6503, 1.2145, 1.4731],
        [1.6164, 0.8102, 0.7954],
        [1.6623, 1.0925, 0.8558]])
tensor([1.3641, 1.0656, 1.2145, 0.8102, 1.0925])


In [16]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x)
print(y)
print(z)

tensor([[ 0.6838, -1.1222,  0.4090, -1.7331],
        [-0.8694,  0.3447,  0.1168,  1.2417],
        [ 1.5808, -0.6259, -1.1666,  0.7549],
        [-0.3298,  0.1707,  0.3494, -1.2467]])
tensor([ 0.6838, -1.1222,  0.4090, -1.7331, -0.8694,  0.3447,  0.1168,  1.2417,
         1.5808, -0.6259, -1.1666,  0.7549, -0.3298,  0.1707,  0.3494, -1.2467])
tensor([[ 0.6838, -1.1222,  0.4090, -1.7331, -0.8694,  0.3447,  0.1168,  1.2417],
        [ 1.5808, -0.6259, -1.1666,  0.7549, -0.3298,  0.1707,  0.3494, -1.2467]])


In [20]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [21]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [26]:
c = np.ones(5)
d = torch.from_numpy(c)
np.add(c, 1, out=c)
print(c)
print(d)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
b